# Generated by Django 5.1.5 on 2025-02-09 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_det',
            name='login_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='chatbot_app.user_login'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_login',
            name='user_type',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
