# Generated by Django 5.1.5 on 2025-02-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0002_user_det_login_id_user_login_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_det',
            name='contact',
            field=models.CharField(max_length=10),
        ),
    ]
