# Generated by Django 5.1.5 on 2025-02-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0003_alter_user_det_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expert_det',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('experience', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='user_login',
            name='user_type',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
