# Generated by Django 5.1.5 on 2025-02-10 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0004_expert_det_alter_user_login_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert_det',
            name='login_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chatbot_app.user_login'),
        ),
    ]
