# Generated by Django 5.1.5 on 2025-02-11 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0005_expert_det_login_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_login',
            name='user_type',
            field=models.IntegerField(default=0),
        ),
    ]
