# Generated by Django 5.1.5 on 2025-02-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0006_alter_user_login_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert_det',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='expert_det',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='Male', max_length=6),
        ),
    ]
