# Generated by Django 5.1.5 on 2025-02-17 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0007_expert_det_status_alter_expert_det_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expert_det',
            name='status',
        ),
    ]
