# Generated by Django 5.1.5 on 2025-02-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0008_remove_expert_det_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_login',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
