# Generated by Django 5.1.5 on 2025-03-01 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0010_expert_user_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language_selection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50)),
                ('current_date', models.DateField(auto_now_add=True)),
                ('current_time', models.TimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_lan_selection', to='chatbot_app.user_login')),
            ],
        ),
    ]
