# Generated by Django 5.1.5 on 2025-03-01 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0011_language_selection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language_selection',
            old_name='user_id',
            new_name='user',
        ),
    ]
