# Generated by Django 5.1.5 on 2025-03-01 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0012_rename_user_id_language_selection_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language_selection',
            old_name='user',
            new_name='user_id',
        ),
    ]
