# Generated by Django 5.1.5 on 2025-03-03 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0014_assessmentquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentquestion',
            name='correct_answer',
            field=models.CharField(max_length=100),
        ),
    ]
