# Generated by Django 5.1.5 on 2025-03-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0015_alter_assessmentquestion_correct_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentquestion',
            name='language',
            field=models.CharField(choices=[('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('it', 'Italian'), ('ja', 'Japanese'), ('zh', 'Mandarin')], max_length=2),
        ),
    ]
