# Generated by Django 5.1.5 on 2025-03-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0017_language_selection_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language_selection',
            name='difficulty',
            field=models.CharField(choices=[('A1', 'Beginner'), ('A2', 'Elementary'), ('B1', 'Intermediate'), ('B2', 'Upper Intermediate'), ('C1', 'Advanced'), ('C2', 'Mastery')], max_length=2, null=True),
        ),
    ]
