# Generated by Django 5.1.5 on 2025-03-10 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0019_language_selection_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expert_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('current_date', models.DateField(auto_now_add=True)),
                ('current_time', models.TimeField(auto_now_add=True)),
                ('expert_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expertid_request', to='chatbot_app.user_login')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userid_request', to='chatbot_app.user_login')),
            ],
        ),
    ]
