# Generated by Django 5.1.5 on 2025-03-11 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0020_expert_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_det',
            name='login_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='chatbot_app.user_login'),
        ),
    ]
