# Generated by Django 5.1.5 on 2025-03-15 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0023_expert_request_schedule_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert_det',
            name='login_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expert', to='chatbot_app.user_login'),
        ),
    ]
