# Generated by Django 5.1.5 on 2025-03-16 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0025_expert_request_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert_user_chat',
            name='current_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
