# Generated by Django 5.1.5 on 2025-03-18 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0026_alter_expert_user_chat_current_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='mock_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('it', 'Italian'), ('ja', 'Japanese'), ('zh', 'Mandarin')], max_length=2)),
                ('question_text', models.TextField()),
                ('options1', models.CharField(max_length=100)),
                ('options2', models.CharField(max_length=100)),
                ('options3', models.CharField(max_length=100)),
                ('options4', models.CharField(max_length=100)),
                ('correct_answer', models.CharField(max_length=100)),
            ],
        ),
    ]
