# Generated by Django 5.1.5 on 2025-03-29 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0027_mock_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert_det',
            name='experience',
            field=models.FileField(upload_to='upload'),
        ),
    ]
