# Generated by Django 5.1.5 on 2025-04-01 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0029_expert_user_chat_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expert_user_chat',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='expert_user_chat',
            name='is_delivered',
        ),
        migrations.RemoveField(
            model_name='expert_user_chat',
            name='is_seen',
        ),
        migrations.DeleteModel(
            name='UserStatus',
        ),
    ]
