# Generated by Django 5.1.5 on 2025-04-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0030_remove_expert_user_chat_is_deleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('Language_name', models.CharField(max_length=50)),
                ('flag_url', models.URLField()),
                ('description', models.TextField()),
            ],
        ),
    ]
