# Generated by Django 5.1.5 on 2025-05-01 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0031_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_login',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='user_login',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
